version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongo_net

  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - SECRET_TOKEN=talkischeapshowmethecode
    networks:
      - mongo_net
    depends_on:
      - mongo

networks:
  mongo_net:
    driver: bridge
